### ISSUE TITLE
Swapped values in Withdraw.xml?

### ISSUE THREAD

**Issue by Darrothan** [NeonOcean/S4.Cycle#3]
Was just snooping around in the repo (trying to see how stuff works) and saw that "LateWithdraw" has an arriving percentage of 0.75 while "VeryLateWithdraw" has an arriving percentage of 0.25. It seems like these values were accidentally swapped.
I'm also not sure if I'm able to change these values without you having to recompile and push a patch (it'd be nice if we could, though!).

[Here's a link to what I'm talking about](https://github.com/NeonOcean/S4.Cycle/blob/0f526cf0b208171a9f8fd10342c6527ce3aebecf/Packages/NeonOcean.S4.Cycle-Gameplay-Package/Sources/Loose/Snippets/Woohoo%20Safety%20Methods/Withdraw.xml#L13-L34)

**Comment by NeonOcean** [comment]
Thanks for catching this, the issue will be fixed in the next version.
