### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by prettygirlhalo** [NeonOcean/S4.Cycle#4]
i got a mcc last exception pop up on my game and i looked into it and it said this: Error message: [NeonOcean.S4.Cycle.Mods.WickedWhims] Failed to handle WickedWhim's try impregnate sim method. (AttributeError: 'ActiveSexInteractionInstance' object has no attribute '_is_sim_on_birth_control')

**Comment by NeonOcean** [comment]
It looks like Wicked Whims got an update that broke compatibility. I'll get this problem fixed very soon.

**Comment by NeonOcean** [comment]
Sorry I forgot about this issue, but this bug was fixed in the January 9th update.
